name: Go CI

on:
  workflow_call:
    inputs:
      go-versions:
        default: '[1.19,1.20,1.21.x,1.22.x]'
        type: string


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ ${{ fromJson(inputs.go-versions) }} ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: go get .
      - name: Test with Go
        run: go test -json > TestResults-${{ matrix.go-version }}.json
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: Go-results-${{ matrix.go-version }}
          path: TestResults-${{ matrix.go-version }}.json
