name: Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: rocketblend-pr-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-pr-title:
    uses: rocketblend/github-workflows/.github/workflows/validate-pr-title.yaml@main
    permissions:
      pull-requests: write
  
  go-ci:
    uses: ./.github/workflows/go-ci.yml